### ISSUE TITLE
ValueError: shape mismatch: value array of shape (3,1) could not be broadcast to indexing result of shape (3,)

### ISSUE THREAD

**Issue by sohee-zoe** [JinlongYANG/sp#1]
`python dpmp_3DTMP.py or python dpmp_3D.py `

**visualization not supported**
visualization not supported
visualization not supported
visualization not supported
Number of arguments: 1 arguments.
Argument List: ['dpmp_3DTMP.py']
Loading /home/sohee/coding/Face_Data/test/sp//models/model_ho_female_5_reduced.pkl 
MODEL model_ho_female_5_reduced
GENDER female
loading /home/sohee/coding/Face_Data/test/sp/MPI-FAUST/test/scans/test_scan_033.ply

- PBP Iter 0

Setting schedule with node 3 as root (torso is node 3 in the body model)

> /home/sohee/coding/Face_Data/test/sp/code/particles.py:245: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  Zp = x[[idx['zPoseIdx']]]
/home/sohee/coding/Face_Data/test/sp/code/particles.py:246: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  Zs = x[[idx['zShapeIdx']]]
/home/sohee/coding/Face_Data/test/sp/code/particles.py:247: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  T = x[[idx['OIdx']]]
/home/sohee/coding/Face_Data/test/sp/code/particles.py:249: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  r_abs = x[[idx['rIdx']]]

time for messages: 0.199114084244
mapParticleInd:
[ 9 24 11 20 11 21 -1 20 23 22  3 16 20 21 -1 13 21 -1 19]

> /home/sohee/coding/Face_Data/test/sp/code/particles.py:141: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
>   x[[idx['zPoseIdx']]] = sbm.Zp[i][0:len(idx['zPoseIdx'])]
> /home/sohee/coding/Face_Data/test/sp/code/particles.py:142: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
>   x[[idx['zShapeIdx']]] = sbm.Zs[i][0:len(idx['zShapeIdx'])]

- PBP Iter 1

**Traceback (most recent call last):
  File "dpmp_3DTMP.py", line 310, in <module>
    lastResult = run(nParticles, nSteps, basePath, inputFilePath[frameId], outputFilePath[frameId], isTest, params, code, 0, frameId, gender)
  File "dpmp_3DTMP.py", line 186, in run
    logB[s] = run_DPMP_step(d, s, frameId, lastResult)
  File "/home/sohee/coding/Face_Data/test/sp/code/run_dpmp_step.py", line 76, in run_DPMP_step
    augmentTypes = sample_particles.sample_particles(dpmp, augment_type)
  File "/home/sohee/coding/Face_Data/test/sp/code/sample_particles.py", line 68, in sample_particles
    proposedParticle, movedType = funDict[proposal_type](this, v, this.b[v]['x'], p_i)
  File "/home/sohee/coding/Face_Data/test/sp/code/sample_particles.py", line 210, in sample_from_nbr
    proposedParticle = particles.set_pose_params(this.particleIdx[b], proposedParticle, r, T)
  File "/home/sohee/coding/Face_Data/test/sp/code/particles.py", line 129, in set_pose_params
    x[idx['rIdx']] = r;
ValueError: shape mismatch: value array of shape (3,1) could not be broadcast to indexing result of shape (3,)**

**Comment by Joon-Jung** [comment]
I got the same problem but solved with downgrading numpy to 1.11.3
